### ISSUE TITLE
Me deparei com um erro ao executar o arquivo. 

### ISSUE THREAD

**Issue by Paulo-AndradeDev** [brunorodriguesdias/sistema_de_cadastro#1]
PS C:\samuel\python\sistema_de_cadastro-master> python sistema_de_cadastro.py 
Traceback (most recent call last):
  File "C:\samuel\python\sistema_de_cadastro-master\sistema_de_cadastro.py", line 3, in <module>
    import tela_cadastro
  File "C:\samuel\python\sistema_de_cadastro-master\tela_cadastro.py", line 3, in <module>
    import tela_consulta
  File "C:\samuel\python\sistema_de_cadastro-master\tela_consulta.py", line 4, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
PS C:\samuel\python\sistema_de_cadastro-master> 

![issue](https://user-images.githubusercontent.com/106722734/196272228-481f67f8-7fd1-484a-80a9-a061d1a104e3.png)

**Comment by brunorodriguesdias** [comment]
Boa tarde Paulo, tudo bem?

Agora quando vi o erro que você me enviou, percebi uma coisa que errei ao
desenvolver o projeto, que ele só irá rodar na minha máquina,
Não tinha pensado nisso, mas criei o banco de dados e a conexão foi via
mysql, então a pessoa teria que ter ele instalado também,
e também instalar o mysql.conector para conectar ao pycharm, e dessa forma
percebi que o banco de dados só existe no meu computador.
Agradeço muito por me mandar essa issue, pois tenho que resolver essa
questão, seu comentário ajudará muito no meu desenvolvimento.
Desculpe o projeto não funcionar como esperava, irei resolver isso!

Em seg., 17 de out. de 2022 às 17:05, Paulo Andrade <
***@***.***> escreveu:
